#!/bin/sh

WWW_DIR=/etc/config/addons/www/xmlapi
CONFIG_URL=/addons/xmlapi/

case "$1" in
""|start)
	if [ ! -e /www/config/xmlapi ]; then
		mount -o remount,rw /
		ln -s $WWW_DIR /www/config/xmlapi
		mount -o remount,ro /
	fi
	;;
info)
	echo "Version: 1.11"
	echo "Name: XML-API"
	echo "Operations: uninstall"
	echo "Config-Url: $CONFIG_URL"
	;;
uninstall)
	if [ -e /www/config/xmlapi ]; then
		mount -o remount,rw /
		rm -f /www/config/xmlapi
		mount -o remount,ro /
	fi
	rm -rf $WWW_DIR
	;;
esac
